# Generated by Django 4.1.7 on 2023-03-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_alter_usercartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_app.usercart'),
        ),
    ]
